blank_issues_enabled: true
contact_links:
  - name: leviatbox Support
    url: https://t.me/+q0Hiy0opPS9iNGZl
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/sobatgabutzz
    about: Documentation for getting started with bot.
